-- 1. Tabla para perfiles de usuario, extendiendo auth.users
CREATE TABLE public.profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  full_name TEXT,
  avatar_url TEXT,
  role TEXT NOT NULL DEFAULT 'cliente'
);
COMMENT ON TABLE public.profiles IS 'Stores public profile data for ea
user.';
COMMENT ON COLUMN public.profiles.id IS 'References the user in
auth.users.';
-- 2. Tabla para los gimnasios
CREATE TABLE public.gyms (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_id UUID NOT NULL REFERENCES public.profiles(id),
  name TEXT NOT NULL,
  description TEXT,
  location TEXT,
  photos TEXT[],
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  is_approved BOOLEAN NOT NULL DEFAULT FALSE
);
COMMENT ON TABLE public.gyms IS 'Stores information about partner
gyms.';
-- 3. Tabla para los tipos de membresía
CREATE TABLE public.membership_types (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL, -- e.g., 'Diario', 'Mensual', 'Anual'
  price NUMERIC(10, 2) NOT NULL,
  duration_days INT NOT NULL
);
COMMENT ON TABLE public.membership_types IS 'Defines the different typ
of memberships available.';
-- Insertar los tipos de membresía base
INSERT INTO public.membership_types (name, price, duration_days)
VALUES
  ('Diario', 5.00, 1),
  ('Mensual', 40.00, 30),
  ('Anual', 400.00, 365);
-- 4. Tabla para las membresías de los usuarios
CREATE TABLE public.user_memberships (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES public.profiles(id),
  membership_type_id BIGINT NOT NULL REFERENCES
public.membership_types(id),
  start_date TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  end_date TIMESTAMPTZ NOT NULL,
  status TEXT NOT NULL DEFAULT 'activa' -- e.g., 'activa', 'caducada',
'cancelada'
);
COMMENT ON TABLE public.user_memberships IS 'Tracks active memberships
for users.';
-- 5. Tabla para las clases/servicios ofrecidos por los gimnasios
CREATE TABLE public.classes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  gym_id BIGINT NOT NULL REFERENCES public.gyms(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  description TEXT,
  start_time TIMESTAMPTZ NOT NULL,
  end_time TIMESTAMPTZ NOT NULL,
  capacity INT NOT NULL
);
COMMENT ON TABLE public.classes IS 'Details of classes offered by
gyms.';
-- 6. Tabla para las reservas
CREATE TABLE public.bookings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES public.profiles(id),
  class_id BIGINT NOT NULL REFERENCES public.classes(id) ON DELETE
CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  status TEXT NOT NULL DEFAULT 'confirmada' -- e.g., 'confirmada',
'cancelada'
);
COMMENT ON TABLE public.bookings IS 'User bookings for classes.';
-- Añadir un constraint UNIQUE para evitar doble reserva
ALTER TABLE public.bookings ADD CONSTRAINT unique_booking UNIQUE
(user_id, class_id);

//.--------------------------------------------------

-- Paso 1: Activar la extensión PostGIS si aún no está activa.
-- Si ya está activa, este comando no hará nada.
CREATE EXTENSION IF NOT EXISTS postgis WITH SCHEMA extensions;

-- Paso 2: Modificar la tabla 'gyms' para añadir una columna de geolocalización.
-- Se elimina la columna de texto 'location' y se añade una columna geográfica.
ALTER TABLE public.gyms DROP COLUMN IF EXISTS location;
ALTER TABLE public.gyms ADD COLUMN location_coords
extensions.geography(Point, 4326);
COMMENT ON COLUMN public.gyms.location_coords IS 'Coordenadas
geográficas (Longitud, Latitud) del gimnasio.';

-- Paso 3: Crear la función para buscar gimnasios cercanos (RPC).
-- Esta función podrá ser llamada desde el frontend.
CREATE OR REPLACE FUNCTION nearby_gyms(
    lat float,
    long float
)
RETURNS TABLE (
    id bigint,
    name text,
    description text,
    photos text[],
    -- No devolvemos las coordenadas exactas, sino la distancia.
    dist_meters float
)
AS $$
BEGIN
    RETURN QUERY
    SELECT
        g.id,
        g.name,
        g.description,
        g.photos,
        extensions.ST_Distance(
            g.location_coords,
            extensions.ST_SetSRID(extensions.ST_MakePoint(long, lat),4326)::extensions.geography
        ) AS dist_meters
    FROM
        public.gyms AS g
    WHERE
        g.is_approved = true
    ORDER BY
        dist_meters;
END;
$$ LANGUAGE plpgsql;

//.----------------------------------------

-- Habilitar RLS en todas las tablas
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.gyms ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.membership_types ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_memberships ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.classes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bookings ENABLE ROW LEVEL SECURITY;

-- Borrar políticas existentes (por si se ejecuta de nuevo)
DROP POLICY IF EXISTS "Los perfiles publicos son visibles por todos." ON public.profiles;
DROP POLICY IF EXISTS "Los usuarios pueden actualizar su propio perfil." ON public.profiles;

DROP POLICY IF EXISTS "Cualquiera puede ver gimnasios aprobados." ON public.gyms;
DROP POLICY IF EXISTS "Los propietarios pueden crear gimnasios." ON public.gyms;
DROP POLICY IF EXISTS "Los propietarios pueden actualizar su propio gimnasio." ON public.gyms;
DROP POLICY IF EXISTS "Los administradores tienen acceso total a los gimnasios." ON public.gyms;

DROP POLICY IF EXISTS "Cualquiera puede ver los tipos de membresia." ON public.membership_types;

DROP POLICY IF EXISTS "Los usuarios pueden ver sus propias membresias." ON public.user_memberships;

DROP POLICY IF EXISTS "Cualquiera puede ver las clases." ON public.classes;
DROP POLICY IF EXISTS "Propietarios pueden gestionar clases de su gimnasio." ON public.classes;

DROP POLICY IF EXISTS "Usuarios pueden ver sus propias reservas." ON public.bookings;
DROP POLICY IF EXISTS "Propietarios pueden ver las reservas de sus clases." ON public.bookings;
DROP POLICY IF EXISTS "Usuarios pueden crear reservas para si mismos." ON public.bookings;
DROP POLICY IF EXISTS "Usuarios pueden cancelar sus propias reservas." ON public.bookings;

-- 1. Políticas para la tabla 'profiles'
CREATE POLICY "Los perfiles publicos son visibles por todos."
  ON public.profiles FOR SELECT
  USING (true);

CREATE POLICY "Los usuarios pueden actualizar su propio perfil."
  ON public.profiles FOR UPDATE
  USING (auth.uid() = id);

-- 2. Políticas para la tabla 'gyms'
CREATE POLICY "Cualquiera puede ver gimnasios aprobados."
  ON public.gyms FOR SELECT
  USING (is_approved = true);

CREATE POLICY "Los propietarios pueden crear gimnasios."
  ON public.gyms FOR INSERT
  WITH CHECK (auth.uid() = owner_id);

CREATE POLICY "Los propietarios pueden actualizar su propio gimnasio."
  ON public.gyms FOR UPDATE
  USING (auth.uid() = owner_id);

CREATE POLICY "Los administradores tienen acceso total a los gimnasios."
  ON public.gyms FOR ALL
  USING ((SELECT role FROM public.profiles WHERE id = auth.uid()) = 'admin');

-- 3. Políticas para la tabla 'membership_types'
CREATE POLICY "Cualquiera puede ver los tipos de membresia."
  ON public.membership_types FOR SELECT
  USING (true);

-- 4. Políticas para la tabla 'user_memberships'
CREATE POLICY "Los usuarios pueden ver sus propias membresias."
  ON public.user_memberships FOR SELECT
  USING (auth.uid() = user_id);
-- (Las inserciones/actualizaciones se manejarán desde una Edge Function con rol 'service_role')

-- 5. Políticas para la tabla 'classes'
CREATE POLICY "Cualquiera puede ver las clases."
  ON public.classes FOR SELECT
  USING (true);

CREATE POLICY "Propietarios pueden gestionar clases de su gimnasio."
  ON public.classes FOR ALL
  USING (
    (SELECT owner_id FROM public.gyms WHERE id = classes.gym_id) = auth.uid()
  );

-- 6. Políticas para la tabla 'bookings'
CREATE POLICY "Usuarios pueden ver sus propias reservas."
  ON public.bookings FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Propietarios pueden ver las reservas de sus clases."
  ON public.bookings FOR SELECT
  USING (
    (SELECT owner_id FROM public.gyms g JOIN public.classes c ON g.id = c.gym_id WHERE c.id = bookings.class_id) = auth.uid()
  );

CREATE POLICY "Usuarios pueden crear reservas para si mismos."
  ON public.bookings FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Usuarios pueden cancelar sus propias reservas."
  ON public.bookings FOR DELETE
  USING (auth.uid() = user_id);